#!/bin/bash
if [[ $# == 0 ]]; then

#                                Kent Milfeld 2/6/2018
#                                TACC

# XCEDE ECSS Poject:
# Support for optimizing the KIM MSMEAM driver for 
#           MSMEAM_Dynamo_Gibson_Baskes__MD_080127949983_000
#
#           Test case model from  KIM:
#           MSMEAM_Gibson_Ti__MO_309653492217_000
#
# FILES  In /work/00770/milfeld/stampede2/KIM.

#   kim_readme               : this file.
#   mkkim                    : Shell script to build kim, driver & model in $HOME/kim
#   MSMEAM_model_driver.F03  : Optimized Driver

# Instructions:
# Execute the instructions below (1-5)to compile kim, the model and driver.
# (You can make this file executable with "chmod 700 kim_readme" and execute it.)
#
# Instruction are provided after executing the last command:
# This will give you the base cost for executing the driver test.
#
#
# NEXT for timing optimized code:
#      cd $HOME/kim/lib/kim-api-v1/model_drivers/MSMEAM*000
#      mv MSMEAM_model_driver.F03 MSMEAM_model_driver_orig.F03
#      cp /work/00770/milfeld/stampede2/KIM/MSMEAM_model_driver_opt.F03 MSMEAM_model_driver.F03
#      make clean
#      make
#      cd $HOME/kim/vc_forces_numer_deriv 
#      echo MSMEAM_Gibson_Ti__MO_309653492217_000 | /usr/bin/time -p ./vc_forces_numer_deriv



# 1.) Make a directory for your kim build:
#     e.g. in your $HOME/kim directory
 
         cd 
         mkdir kim
         cd    kim

# 2.) Get kim and untar it:

         wget https://s3.openkim.org/kim-api/kim-api-v1.9.2.txz
         tar  Jxvf $HOME/kim-api-v1.9.2.txz


# 3.) Build kim

         cp /work/00770/milfeld/stampede2/KIM/mkkim .

         ml intel/18.0.0
         ./mkkim build |& tee build.log

# 4.) Download a collection (default is EDIP_BOP_Belko_Gusakov_Dorozhkin_Ge__MO_129433059219_000)
#    (Reset KIM_MO at the top of mkkim to change the collection.)


        ./mkkim collection |& tee collection.log

# 5.) Download Driver (default is MSMEAM_Gibson_Ti__MO_309653492217_000)
#     (Reset KIM_MD at the top of mkkim to change the Driver.)


         ./mkkim driver |& tee driver.log
     

#6.) When you are ready to try optimized code, do the following:

#      now execute the following in $HOME/kim/vc_forces_numer_deriv       

       cd $HOME/kim/vc_forces_numer_deriv       
       echo MSMEAM_Gibson_Ti__MO_309653492217_000 | /usr/bin/time -p ./vc_forces_numer_deriv

fi

#7.) When you are ready to try optimized code, do the following (ignore the if statement, 
#    unless you are doing the builds by executing this file):

if [[ $# == 1 && $1 == "mkopt" ]]; then

       cd $HOME/kim/lib/kim-api-v1/model_drivers/MSMEAM*000
       mv MSMEAM_model_driver.F03 MSMEAM_model_driver_orig.F03
       cp /work/00770/milfeld/stampede2/KIM/MSMEAM_model_driver_opt.F03 MSMEAM_model_driver.F03
       make clean
       make

#      now execute the following in $HOME/kim/vc_forces_numer_deriv       
       cd $HOME/kim/vc_forces_numer_deriv 
       echo MSMEAM_Gibson_Ti__MO_309653492217_000 | /usr/bin/time -p ./vc_forces_numer_deriv
fi
